[package]
name = "stringsuite"
version = "1.1.0"
edition = "2021"

[dependencies]
bimap = "0.6.2"
text_io = "0.1.10"
eframe = "0.19.0"
tinyfiledialogs = "3.9.1"
strum = "0.24.1"
strum_macros = "0.24.3"
