[package]
name = "stringsuite"
version = "1.4.4"
edition = "2021"

[dependencies]
eframe = "0.19.0"
tinyfiledialogs = "3.9.1"
strum = "0.24.1"
strum_macros = "0.24.3"
enum_dispatch = "0.3.8"
num = "0.4.0"
